### ISSUE TITLE
.snakemake/scripts folder is empty

### ISSUE THREAD

**Issue by MarleyCodes** [Hoohm/dropSeqPipe#80]
The pipeline does not seem to create the tmp files of the scripts within the batch/.snakemake/scripts directory. Which results in the crash of the following command: 

`source /home/mye/miniconda2/bin/activate '/data/sag/2019/MYE_18020068_2019_SingleCellTomBras/dropSeqPipe/batch1/.snakemake/conda/f854f536'; set -euo pipefail;  Rscript --vanilla /data/sag/2019/MYE_18020068_2019_SingleCellTomBras/dropSeqPipe/batch1/.snakemake/scripts/tmp5wipn0w_.plot_violine.R'`

With error:

`Fatal error: cannot open file '/data/sag/2019/MYE_18020068_2019_SingleCellTomBras/dropSeqPipe/batch1/.snakemake/scripts/tmp5wipn0w_.plot_violine.R': No such file or directory`

Is something going wrong with rights or directories? Any clues would be greatly appreciated.

config.yaml:

```
CONTACT:
  email: ''
  person: ''
LOCAL:
    temp-directory: /data/sag/2019/MYE_18020068_2019_SingleCellTomBras/maize/small_set/dropseqpipe/tmp
    memory: 8g
    raw_data: /data/sag/2019/MYE_18020068_2019_SingleCellTomBras/dropSeqPipe/batch1/RAW_DATA
    results: maize_results
META:
    species: 
        maize:
            build: 73
            release: 42
    ratio: 0.2
    reference-directory: /data/sag/2019/MYE_18020068_2019_SingleCellTomBras/maize
    gtf_biotypes: gtf_biotypes.yaml

FILTER:
    barcode-whitelist: ''
    5-prime-smart-adapter: AATGATACGGCGACCACCGAGATCTACACGCCTGTCCGCGGAAGCAGTGGTATCAACGCAGAGTAC
    cell-barcode:
        start: 1
        end: 12
    UMI-barcode:
        start: 13
        end: 20
    cutadapt:
        adapters-file: NexteraPE-PE.fa
        R1:
            quality-filter: 20
            maximum-Ns: 1
            extra-params: ''
        R2:
            quality-filter: 20
            minimum-adapters-overlap: 6
            minimum-length: 15
            extra-params: ''
MAPPING:
    STAR:
        genomeChrBinNbits: 18
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
EXTRACTION:
    LOCUS:
        - CODING
        - UTR
    strand-strategy: SENSE
    UMI-edit-distance: 1
    minimum-counts-per-UMI: 0

```
